version: '2'
services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    networks:
      - back-tier
  web:
    build: .
    command:
    - gunicorn
    - -c
    - /code/settings.py
    - lintreview.web:app
    env_file: lintreview-env
    ports:
     - "5000:5000"
    links:
     - broker
    networks:
      - front-tier
      - back-tier
  worker:
    build: .
    environment:
      - C_FORCE_ROOT=true
    command:
    - celery
    - -A
    - lintreview.tasks
    - worker
    - -l
    - info
    env_file: lintreview-env
    links:
     - broker
    networks:
      - back-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
